```{r}
library(tidyquant)
library(timeSeries)
library(FRAPO)
library(readxl)
library(ghyp)
library(fBasics)
library(dplyr)
library(reshape2)
library(QRM)
library(fGarch)
library(forecast)
library(zoo)
library(ghyp)
library(evir)
library(fExtremes)
library(evir)
library(ismev)
options("getSymbols.warning4.0"=FALSE)
options("getSymbols.yahoo.warning"=FALSE)
```

```{r}
# Set Time Frame for Data
data_start_date = as.POSIXct("2019-04-01")
data_end_date = as.POSIXct("2022-04-01")

# Set Toclers and Weights for Portfolio (Here Charlie Munger)
holdings_1 = c("BAC","WFC","BABA","USB","PKX")
actual_weights_1 = c(44.59,36.28,15.35,3.5,0.28)

# Set as Timeframe
stock_prices_1 = tq_get(holdings_1,
                        from = data_start_date,
                        to = data_end_date,
                        get = "stock.prices")

# Pivot df to get tickers as columns
investor_df_1 = dcast(data = stock_prices_1, formula = date ~ symbol, fun.aggregate = mean, value.var = "adjusted")
```

```{r}
# Clean Data
investor_df_1 = na.omit(investor_df_1)

# final df
head(investor_df_1)

# Write csv if wanted
write.csv(investor_df_1,"CM_Portfolio.csv")
```

```{r}
#Time Series
CMdate = as.character(investor_df_1$date)
CM = investor_df_1[,-c(1)] 
CMTS = timeSeries(CM, charvec = CMdate)
returnCM = returnSeries(CMTS)*100

#Daily Return for CM Portfolio in %
write.csv(returnCM, "Return_Portfolio.csv")
```

```{r}
#Plot Daily Portfolio Returns for Security
seriesPlot(returnCM, main="Charlie Mungers Daily Returns in %", col="red")
```

```{r}
#Autocorrelation Function + Partial autocorrelation Function for Absolute Returns
CMReturnsAbs = abs(returnCM)

#ACF + PCF
plot(acf(na.omit(CMReturnsAbs), main="ACF of Absolute Returns of Charlie Munger" , lag.max=20, ylab="", xlab= "", col="red", ci.col="blue"))
plot(pacf(na.omit(CMReturnsAbs), main="PACF of Absolute Returns of Charlie Munger", lag.max=20,ylab="", xlab = "", col = "red", ci.col="blue"))

#Auto Correlation Function of stylized returns to get heteroscedasticity
acf(returnCM, na.action = na.pass)
#ACF exhibit no autocorrelation (Gleicher Ausschlag), implying daily returns are independent of each other

#Plotting ACF of absolute returns
acf(abs(returnCM), na.action = na.pass)
#A lot of persistence of autocorrelation, meaning daily absolute returns are not independent

#If no Autocorrelation appears, ARMA(0,0) is the best value
pacf(returnCM, na.action = na.pass)

#If you see Autocorrelation its either auto regressive, moving average or hybrid process that is defining daily returns.
acf((returnCM)^2, na.action = na.pass)
pacf((returnCM)^2, na.action = na.pass)
```

```{r}
# Zoo Plot
returnCMZoo = as.zoo(returnCM)
plot(returnCMZoo, xlab = "", main = "")
```

```{r}
#Mean Return CM
returnCM$PortRet = (returnCM$BABA/100)*actual_weights_1[1]+(returnCM$BAC/100)*actual_weights_1[2]+(returnCM$PKX/100)*actual_weights_1[3]+(returnCM$USB/100)*actual_weights_1[4]+(returnCM$WFC/100)*actual_weights_1[5]
head(returnCM)
mean(returnCM$PortRet) #Mean Daily Return = -0.008%
```

```{r}
#Value at Risk for Charlie Munger Portfolio
returnCM = returnCM/100
PortVar.Hist = VaR(returnCM, p=0.95, weights = actual_weights_1, portfolio_method = "component",method = "historical")
PortVar.Hist$hVaR
PortVar.Gaus = VaR(returnCM, p=0.95, weights = actual_weights_1, portfolio_method = "component",method = "gaussian")
PortVar.Gaus$VaR
PortVar.Mod = VaR(returnCM, p=0.95, weights = actual_weights_1, portfolio_method = "component",method = "modified")
PortVar.Mod$MVaR
```

# Expected Shortfall ---
```{r}
CMloss = as.data.frame(na.omit(-1.0*diff(log(CMTS))*100))
head(CMloss)
```
# Charlie Munger Portfolio ---
```{r}
# Losses for CM Portfolio + ACF + PACF
par(mfrow=c(2,1))
CMloss$Port = CMloss[1]*actual_weights_1[1]+CMloss[2]*actual_weights_1[2]+CMloss[3]*actual_weights_1[3]+CMloss[4]*actual_weights_1[4]+CMloss[5]*actual_weights_1[5]
acf(CMloss$Port)
pacf(CMloss$Port)
#No Autocorrelation so Arma (0,0)
```

```{r}
#Arima Model
arimaCM = arima(CMloss$Port, order=c(1,0,0))
acf(arimaCM$residuals) #No autocorrelation
acf((arimaCM$residuals)^2) #Autocorrelation (same side clustering) ==> Heteroscedasticity, can predict future value of volatility

#Predict Future Value of CM
predict(arimaCM, n.ahead=1)
```

```{r}
#ARMA(1,0) + GARCH(1,1) CM
gCM = garchFit(formula =  ~arma(0,0)+garch(1,1), cond.dist = "std", include.mean = FALSE, data = CMloss$Port)
summary(gCM)

#Standard Deviation (Measure of Risk) for next period
predict(gCM, n.ahead=1)
```

```{r}
#Expected Shortfall
ESgarch = function(y){
  gfit = garchFit(formula =  ~arma(1,0)+garch(1,1), data = y, cond.dist = "std", trace = FALSE)
  sigma = as.numeric(predict(gfit, n.ahead = 1)[3])
  rand = rt(100000, df=df)
  ES = sigma * mean(head(sort(rand, decreasing = T),5000))
  VAR = sigma * min(head(sort(rand, decreasing = T),5000))
  c(ES,VAR)
}
```


```{r}
library(fPortfolio)
library(lattice)
# Calculate covariance matrix of return series
head(returnCM)
covCM = cov(returnCM)
head(covCM)

## Portfolio Optimizations
GMVwCM = Weights(PGMV(returnCM)) # Global Minimum Variance Portfolio
MDPwCM = Weights(PMD(returnCM)) # Most Diversified Portfolio
MTDwCM = Weights(PMTD(returnCM)) # Minimum Tail Dependent Portfolio
ERCwCM = Weights(PERC(covCM)) # Equal risk contributed portfolios
#add # Actual investor portfolio
names(actual_weights_1) = holdings_1 # add names to weights
AwCM = actual_weights_1[order(names(actual_weights_1))] #order list to match other portfolios 
  
## Combining optimized portfolio solutions
weightsCM = cbind(GMVwCM, MDPwCM, MTDwCM, ERCwCM, AwCM)
MRC_CM = apply(weightsCM, 2, mrc, Sigma = covCM)
rownames(MRC_CM) = colnames(returnCM)
colnames(MRC_CM) = c("GMV", "MDP", "MTD", "ERC","Actual")

## Plot of portfolio allocation comparison
{oldpar = par(no.readonly = TRUE)
par(mfrow = c(2, 2))
dotchart(GMVwCM, xlim = c(0, 40), main = "GMV Allocation", pch = 19)
dotchart(MDPwCM - GMVwCM, xlim = c(-20, 20), main = "MDP vs. GMV",
         pch = 19)
abline(v = 0, col = "grey")
dotchart(MTDwCM - GMVwCM, xlim = c(-20, 20), main = "MTD vs. GMV",
         pch = 19)
abline(v = 0, col = "grey")
dotchart(ERCwCM - GMVwCM, xlim = c(-20, 20), main = "ERC vs. GMV",
         pch = 19)
abline(v = 0, col = "grey")
par(oldpar)}

## Lattice plots of MRC
StockCM = factor(rep(rownames(MRC_CM), 5),
                 levels = sort(rownames(MRC_CM)))
PortCM = factor(rep(colnames(MRC_CM), each = 5),
               levels = colnames(MRC_CM))
MRC_CMdf = data.frame(MRC_CM = c(MRC_CM), PortCM, StockCM)
dotplot(StockCM ~ MRC_CM | PortCM, groups = PortCM, data = MRC_CMdf,
        xlab = "Percentages",
        main = "Charlie Munger | MR Contributions by Stock per Portfolio",
        col = "black", pch = 19)
dotplot(PortCM ~ MRC_CM | StockCM, groups = StockCM, data = MRC_CMdf,
        xlab = "Percentages",
        main = "Charlie Munger | MR Contributions by Portfolio per Stock",
        col = "black", pch = 19)

```


```{r}
## Return for Total Portfolio GMV
CMGMV = (returnCM$BABA/100)*weightsCM[1,1]+(returnCM$BAC/100)*weightsCM[2,1]+(returnCM$PKX/100)*weightsCM[3,1]+(returnCM$USB/100)*weightsCM[4,1]+(returnCM$WFC/100)*weightsCM[5,1]
mean(CMGMV)
```

```{r}
## Return for Total Portfolio MDP
CMMDP = (returnCM$BABA/100)*weightsCM[1,2]+(returnCM$BAC/100)*weightsCM[2,2]+(returnCM$PKX/100)*weightsCM[3,2]+(returnCM$USB/100)*weightsCM[4,2]+(returnCM$WFC/100)*weightsCM[5,2]
mean(CMMDP)
```

```{r}
## Return for Total Portfolio MTD
CMMTD = (returnCM$BABA/100)*weightsCM[1,3]+(returnCM$BAC/100)*weightsCM[2,3]+(returnCM$PKX/100)*weightsCM[3,3]+(returnCM$USB/100)*weightsCM[4,3]+(returnCM$WFC/100)*weightsCM[5,3]
mean(CMMTD)
```

```{r}
## Return for Total Portfolio ERC
CMERC = (returnCM$BABA/100)*weightsCM[1,4]+(returnCM$BAC/100)*weightsCM[2,4]+(returnCM$PKX/100)*weightsCM[3,4]+(returnCM$USB/100)*weightsCM[4,4]+(returnCM$WFC/100)*weightsCM[5,4]
mean(CMERC)
```

```{r}
## Return for Total Portfolio's Comparison
CMGMVr = (mean(CMGMV)+1)^252
CMMDPr = (mean(CMMDP)+1)^252
CMMTDr = (mean(CMMTD)+1)^252
CMERCr = (mean(CMERC)+1)^252
CMreturnA = c(CMGMVr,CMMDPr,CMMTDr,CMERCr)
CMreturnA
```



```{r}
# VaR and ES for GMV Portfolio + Hyperbolic Distribution Models

#Adjust Return Names for Portfolio (Add Ticker symbols on Demand)
A = returnCM$BABA
B = returnCM$BAC
C = returnCM$PKX
D = returnCM$USB
E = returnCM$WFC
portRet = returnCM$PortRet

# Portfolio Return Function
portriskret <- function(x,y,z,xx,yy,wx,wy,wz,wxx,wyy){
  varx<-var(x, na.rm = TRUE)
  vary<-var(y, na.rm = TRUE)
  varz<-var(z, na.rm = TRUE)
  varxx<-var(xx, na.rm = TRUE)
  varyy<-var(yy, na.rm = TRUE)
  meanx<-mean(x, na.rm = TRUE)
  meany<-mean(y, na.rm = TRUE)
  meanz<-mean(z, na.rm = TRUE)
  meanxx<-mean(xx, na.rm = TRUE)
  meanyy<-mean(yy, na.rm = TRUE)
  ERp<-wx*meanx+wy*meany+wz*meanz+wxx*meanx+wyy*meanyy
  c(ERp)
}

# Covariance Function to optimize perfect portfolio Weights for GMV Port
Portcov = cov(returnCM, use="pairwise.complete.obs") 
head(Portcov)

# Weights for the Global Minimum Variance Portfolio

GMV = PGMV(Portcov)
GMV
DECIMALS = Weights(GMV)/100 
str(DECIMALS) 
attr(DECIMALS,"names")= NULL 
str(DECIMALS) 
wA = c(DECIMALS[1]) 
wB = c(DECIMALS[2]) 
wC = c(DECIMALS[3])
wD = c(DECIMALS[3])
wE = c(DECIMALS[3])

# GMV Portfolio Return

GMVRet = portriskret(A,B,C,D,E,wA,wB,wC,wD,wE) 
GMVRet

# Daily returns of the GMVP portfolio.

GMVDaily = (wA*A+wB*B+wC*C+wD*D+wE*E)


datets = as.character(date_1)
GMVPortTs = timeSeries(GMVDaily, na.rm=TRUE)

# Distribution fit to Portfolio returns

AIC = stepAIC.ghyp(GMVPortTs,control = list(maxit = 1000))

# Asymmetric Generalized Hyperbolic Distribution Models: ("ghyp", "hyp", "NIG", "VG", "t", "gauss")

AIC$fit.table 
ghypfit = fit.ghypuv(GMVPortTs, symmetric = FALSE, control = list(maxit = 1000), na.rm = TRUE) 
summary(ghypfit)

# Estimated VaR measurements of risk for portfolio
#(Largest expected daily loss in 95% of all cases.)
p = c(0.01,0.05,0.1)
portvar = abs(qghyp(p, ghypfit)) 
portvar

# Estimated ES measurement of risk for portfolio
#(Largest Expected Daily in 5% of all cases)
portes = abs(ESghyp(p, ghypfit)) 
portes
```